### ISSUE TITLE
The ClearButton and DropDownButton of the ComboBox are not aligned

### ISSUE THREAD

**Issue by xiejiang2014** [irihitech/Semi.Avalonia#463]
`<ComboBox Classes="ClearButton" />`

![image](https://github.com/user-attachments/assets/d1c7a17f-7ad8-4c55-b770-cd80bcdf15e6)

In addition, the overlap of ClearButton and DropDownButton can easily cause misoperation. The user wants to click the DropDownButton but clicks the ClearButton when the mouse moves over it. This design violates the user's first intuition.

**Comment by zdpcdt** [comment]
This behavior is actually by design in Semi Design. When the `ClearButton` is enabled and the input box has selected data, hovering over it will display the `ClearButton` in place of the DropDownButton.

However, the misalignment between the `DropDownButton` and the `ClearButton` is indeed a minor issue that could be improved.
